### ISSUE TITLE
Create release build is failing

### ISSUE THREAD

**Issue by RinorDreshaj** [Vidyo/vidyo.io-connector-react-native#9]
Error from the xcode

ld: bitcode bundle could not be generated because '/vidyo.io-connector-react-native/ios/lib/ios/lib/ios/VidyoClientIOS.framework/VidyoClientIOS(VidyoChatMessage_Objc.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/vidyo.io-connector-react-native/ios/lib/ios/lib/ios/VidyoClientIOS.framework/VidyoClientIOS' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tmelko-vidyo** [comment]
You have to disable "bitcode" option because it's not supported by VidyoClient.

**Comment by RinorDreshaj** [comment]
> You have to disable "bitcode" option because it's not supported by VidyoClient.

This did the job, I've already have tried this but couldnt export AdHoc, now that the Xcode was updated I disabled again bitcode and it worked also for the exporting.

Thanks @tmelko-vidyo
